name: my-app
namespace: default
general:
  image: nginx
  version: 1.14.2
  environment:
    ENVIRONMENT: production

scaling:
  replicas: 3
  resources:
    cpu: 1
    memory: 512

probes:
  startup:
    path: "/"
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 3
  liveness:
    path: "/"
    initialDelaySeconds: 10
    periodSeconds: 20
  readiness:
    path: "/"
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 3

networking:
  expose: true
  port: 8080
